mysql:
  Host: mysql-course
  Port: 3306
  User: root
  Password: Abc123
  DBName: course
service:
  Version: 1.0.0
  Mode: development
  port: 50054
  Secret: go-courses
  PasswordTokenExpired: 1
  AccessTokenExpiredIn: 24
  RefreshTokenExpiredIn: 720
  MaxSizeMess: 10485760
redis:
  address: 127.0.0.1:3308
  password: ""
  DB: 0
otherServices:
  CourseUrl: courseservice:50053
