
mysql:
  Host: 127.0.0.1
  Port: 3307
  User: root
  Password: Abc123
  DBName: course
service:
  Version: 1.0.0
  Mode: development
  port: 50051
  Secret: go-courses
  ActiveTokenExpired: 24
  AccessTokenExpiredIn: 24
  RefreshTokenExpiredIn: 720
email:
  AppEmail: management.userxyz@gmail.com
  AppPassword: lkkjakmjuqudztfa
otherServices:
  MailServiceURL: localhost:4001
  CartServiceUrl: localhost:50054
clientSide:
  URL: localhost:8080
rabbitMq:
  User: abc
  Password: Abc123
  Port: 5672
  Host: localhost