
mysql:
  Host: 127.0.0.1
  Port: 3307
  User: root
  Password: Abc123
  DBName: course
service:
  Version: 1.0.0
  Mode: development
  port: 50052
  Secret: go-courses
  PasswordTokenExpired: 1
  AccessTokenExpiredIn: 360
  RefreshTokenExpiredIn: 720
  MaxSizeMess: 10485760
email:
  AppEmail: management.userxyz@gmail.com
  AppPassword: lkkjakmjuqudztfa
otherServices:
  FileUrl: localhost:4000
  CartServiceUrl: localhost:50054
  PaymentUrl: localhost:4002


