
mysql:
  Host: mysql-course
  Port: 3306
  User: root
  Password: Abc123
  DBName: course
service:
  Version: 1.0.0
  Mode: development
  port: 50052
  Secret: go-courses
  PasswordTokenExpired: 1
  AccessTokenExpiredIn: 24
  RefreshTokenExpiredIn: 720
  MaxSizeMess: 10485760
email:
  AppEmail: management.userxyz@gmail.com
  AppPassword: lkkjakmjuqudztfa
otherServices:
  FileUrl: fileservice:4000
  CartServiceUrl: cartservice:50054
  PaymentUrl: paymentservice:4002

